collections:
  - name: ansible.netcommon
  - name: ansible.posix
  - name: community.crypto
  - name: community.docker
  - name: community.general
  - name: community.grafana
  - name: community.hashi_vault
